"""Integration tests for the backtrader paper backend (``engine="backtrader"``).

Drives the real :class:`~ube.adapters.backtrader_adapter.adapter.BacktraderAdapter` through the
paper ``init``/``run`` API over synthetic ``crypto_perp`` bars, and asserts the defining
property of the recomputable backend: folding a long history in *multiple* windows produces
exactly the ledger a single full-window run produces (including same-bar flips and carried
positions), because every window re-derives its start and checkpoint balance from state.

Unlike vectorbt (which fills at the signal bar), backtrader fills market orders at the
*next* bar's open, so the entry/first-exit timestamps here are one bar later than the
vectorbt mirrors (e.g. a bar-4 signal fills at bar 5 = ``1704085200000000000``).
"""

from __future__ import annotations

import numpy as np
import pytest

from ube.core.config import BacktestConfig, SignalConfig
from ube.core.data import MarketData
from ube.core.errors import EngineError
from ube.core.ledger import EventType, trades
from ube.core.risk import RiskConfig
from ube.core.risk.exits import ATRStop, StopLoss, TakeProfit
from ube.core.risk.sizing import SizeModel
from ube.core.signals import Signals, from_target
from ube.papertrading import get_paper_engine, get_state_class, init, run
from ube.papertrading.backtrader.backend import (
    BacktraderPaperEngine,
    _apply_policy,
    _zero_at_or_before,
    _zero_entries_at_or_before,
)
from ube.papertrading.backtrader.state import BacktraderPaperState
from ube.papertrading.config import PaperConfig
from ube.testing.synthetic import PRESETS, synthetic_bars

AC = "crypto_perp"


def _config(**kw: object) -> PaperConfig:
    instr = PRESETS[AC].instrument
    bc = BacktestConfig(
        instrument=instr,
        signal=SignalConfig(on_opposite_signal="reverse"),
    )
    return PaperConfig(base=bc, engine="backtrader", starting_balance=10_000.0, **kw)


def _slice_md(md: MarketData, sl: slice) -> MarketData:
    sliced = MarketData.__new__(MarketData)  # type: ignore[call-arg]
    object.__setattr__(sliced, "open", md.open[sl])
    object.__setattr__(sliced, "high", md.high[sl])
    object.__setattr__(sliced, "low", md.low[sl])
    object.__setattr__(sliced, "close", md.close[sl])
    object.__setattr__(sliced, "volume", md.volume[sl])
    object.__setattr__(sliced, "index", md.index[sl])
    return sliced


def _slice_sig(sig: Signals, sl: slice) -> Signals:
    return Signals(
        long_entry=sig.long_entry[sl],
        long_exit=sig.long_exit[sl],
        short_entry=sig.short_entry[sl],
        short_exit=sig.short_exit[sl],
    )


def _summary(state: BacktraderPaperState, cfg: PaperConfig) -> list[tuple[int, float, int, int]]:
    instr = cfg.base.instrument
    return [
        (t.side, round(t.net_pnl, 6), t.entry_timestamp, t.exit_timestamp)
        for t in trades(state.ledger, instruments={instr.symbol: instr})
    ]


def _run_windows(
    bounds: list[tuple[int, int]], *, n: int = 24, target: np.ndarray | None = None
) -> tuple[list[tuple[int, float, int, int]], object]:
    if target is None:
        target = np.zeros(n, dtype=int)
        target[4:10] = 1
        target[10:18] = -1
        target[20:24] = 1
    data = synthetic_bars(PRESETS[AC], n_bars=n)
    signals = from_target(target)
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        state: BacktraderPaperState | None = None
        for a, b in bounds:
            state, _ = run(
                "x",
                _slice_md(data, slice(a, b)),
                _slice_sig(signals, slice(a, b)),
                cfg,
                db_path=db,
            )
    assert state is not None
    return _summary(state, cfg), state.open_position


def _r(x: object) -> float | None:
    """Round ``x`` to a stable precision so float noise never breaks equality."""
    return round(float(x), 10) if x is not None else None


def _ledger_tokens(state: BacktraderPaperState) -> list[tuple[object, ...]]:
    """The persisted ledger as comparable tokens (order ids are per-run artifacts).

    ``order_id`` is generated by a per-``_fold``-call counter, so a windowed run's
    window-2 orders restart at ``bt-1`` while the full run numbers them continuously —
    the ids are not semantically meaningful across runs (the fill sequence is). They are
    normalized away so the *captured event stream* is what gets compared.
    """
    return [
        (
            e.event_type.value,
            int(e.timestamp),
            e.action,
            None,  # order_id: per-run counter, not comparable
            e.side,
            _r(e.quantity),
            _r(e.price),
            _r(e.notional),
            e.gap_fill,
            _r(e.amount),
            e.currency,
            e.rollover_from,
            e.rollover_to,
            _r(e.position_after),
            e.exit_reason,
        )
        for e in state.ledger.events
    ]


def _run_windows_state(
    bounds: list[tuple[int, int]], *, n: int = 24, target: np.ndarray | None = None
) -> BacktraderPaperState:
    if target is None:
        target = np.zeros(n, dtype=int)
        target[4:10] = 1
        target[10:18] = -1
        target[20:24] = 1
    data = synthetic_bars(PRESETS[AC], n_bars=n)
    signals = from_target(target)
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        state: BacktraderPaperState | None = None
        for a, b in bounds:
            state, _ = run(
                "x",
                _slice_md(data, slice(a, b)),
                _slice_sig(signals, slice(a, b)),
                cfg,
                db_path=db,
            )
    assert state is not None
    return state


def _target_full_run() -> np.ndarray:
    target = np.zeros(24, dtype=int)
    target[4:10] = 1
    target[10:18] = -1
    target[20:24] = 1
    return target


# ---------------------------------------------------------------------------
# registration
# ---------------------------------------------------------------------------


def test_engine_and_state_class_registered() -> None:
    assert get_paper_engine("backtrader") is BacktraderPaperEngine
    assert get_state_class("backtrader") is BacktraderPaperState


# ---------------------------------------------------------------------------
# pure helpers
# ---------------------------------------------------------------------------


def test_apply_policy_opens_and_holds_long() -> None:
    sig = Signals(
        long_entry=np.array([True, True, False, False]),
        long_exit=np.zeros(4, dtype=bool),
        short_entry=np.zeros(4, dtype=bool),
        short_exit=np.zeros(4, dtype=bool),
    )
    out = _apply_policy(sig, allow_short=True, policy="reverse")
    assert list(out.long_entry) == [True, False, False, False]
    assert not out.long_exit.any()


def test_apply_policy_reverse_emits_close_and_opposite_entry() -> None:
    sig = Signals(
        long_entry=np.array([True, False, False]),
        long_exit=np.zeros(3, dtype=bool),
        short_entry=np.array([False, True, False]),
        short_exit=np.zeros(3, dtype=bool),
    )
    out = _apply_policy(sig, allow_short=True, policy="reverse")
    assert list(out.long_entry) == [True, False, False]
    assert list(out.long_exit) == [False, True, False]
    assert list(out.short_entry) == [False, True, False]


def test_apply_policy_seeds_carried_side_so_closes_reach_the_strategy() -> None:
    # A window that resumes a carried short must keep encoding its *close* signal —
    # seeding ``sim_side`` flat (``0``) would decide_action it away as a hold.
    sig = Signals(
        long_entry=np.zeros(3, dtype=bool),
        long_exit=np.zeros(3, dtype=bool),
        short_entry=np.zeros(3, dtype=bool),
        short_exit=np.array([False, True, False]),
    )
    carried = _apply_policy(sig, allow_short=True, policy="reverse", initial_side=-1)
    assert list(carried.short_exit) == [False, True, False]
    # Flat simulation drops the orphan exit (there is nothing to close).
    flat = _apply_policy(sig, allow_short=True, policy="reverse", initial_side=0)
    assert not flat.short_exit.any()


def test_apply_policy_exit_only_does_not_open_opposite() -> None:
    sig = Signals(
        long_entry=np.array([True, False, False]),
        long_exit=np.zeros(3, dtype=bool),
        short_entry=np.array([False, True, False]),
        short_exit=np.zeros(3, dtype=bool),
    )
    out = _apply_policy(sig, allow_short=True, policy="exit_only")
    assert list(out.long_exit) == [False, True, False]
    assert not out.short_entry.any()


def test_apply_policy_respects_allow_short() -> None:
    sig = Signals(
        long_entry=np.zeros(1, dtype=bool),
        long_exit=np.zeros(1, dtype=bool),
        short_entry=np.array([True]),
        short_exit=np.zeros(1, dtype=bool),
    )
    out = _apply_policy(sig, allow_short=False, policy="reverse")
    assert not out.short_entry.any()


def test_zero_at_or_before_drops_bound_bar() -> None:
    sig = Signals(
        long_entry=np.array([True, False, True]),
        long_exit=np.zeros(3, dtype=bool),
        short_entry=np.zeros(3, dtype=bool),
        short_exit=np.zeros(3, dtype=bool),
    )
    ts = np.array([10, 20, 30])
    out = _zero_at_or_before(sig, ts, 20)
    assert list(out.long_entry) == [False, False, True]


def test_zero_entries_at_or_before_keeps_exits() -> None:
    ts = np.array([10, 20, 30])
    ones = np.ones(3, dtype=bool)
    # long side: an entry and an exit column, checked independently (Signals rejects the
    # contradictory pairings, so each side is exercised in its own Signals object).
    long_sig = Signals(
        long_entry=np.array([True, True, True]),
        long_exit=ones,
        short_entry=np.zeros(3, dtype=bool),
        short_exit=np.zeros(3, dtype=bool),
    )
    long_out = _zero_entries_at_or_before(long_sig, ts, 20)
    assert list(long_out.long_entry) == [False, False, True]
    assert list(long_out.long_exit) == [True, True, True]

    short_sig = Signals(
        long_entry=np.zeros(3, dtype=bool),
        long_exit=np.zeros(3, dtype=bool),
        short_entry=np.array([True, True, True]),
        short_exit=ones,
    )
    short_out = _zero_entries_at_or_before(short_sig, ts, 20)
    assert list(short_out.short_entry) == [False, False, True]
    assert list(short_out.short_exit) == [True, True, True]


def test_flat_window_replay_does_not_double_the_first_entry() -> None:
    # Live GBPUSD regression: the worker resumed a *flat* ledger over a window that started
    # before the cursor, so the replay opened an entry the persisted ledger never booked.
    # The strategy then flipped that phantom leg on the next committed bar, where its close
    # survived the `> cursor` event filter and was folded as a second entry — the first trade
    # printed ~2x (151,908.92 vs 75,673.30 units) and every later quantity/balance drifted
    # with it. A flat ledger must replay flat through the committed region.
    preset = PRESETS[AC]
    n = 48
    data = synthetic_bars(preset, n_bars=n)
    # The ATR stop supplies the pre-cursor warmup the replay reaches back through (period 3);
    # its stop distance is made unreachable so the phantom leg survives to the flip bar.
    cfg = PaperConfig(
        base=BacktestConfig(
            instrument=preset.instrument,
            signal=SignalConfig(on_opposite_signal="reverse"),
            risk=RiskConfig(exit=(ATRStop(mult=1e9, period=3, atr="atr_1m"),)),
        ),
        engine="backtrader",
        starting_balance=10_000.0,
    )
    aux = {"atr_1m": data}
    cursor_bar = 24

    import tempfile
    from pathlib import Path

    # The live worker recomputes the signal frame from a growing fetch window every poll, so
    # a stateful (ATR/wall-clock driven) signal function legitimately returns *different*
    # values for bars it has already passed — that is what let the replay open a leg the
    # ledger never booked. Model it directly: window 1 sees a flat frame, window 2's frame
    # carries a phantom entry at bar 10 (pre-cursor) and a real flip at bar 30.
    window1 = np.zeros(n, dtype=int)
    phantom = np.zeros(n, dtype=int)
    phantom[10 : cursor_bar + 1] = -1  # phantom short, wholly inside the committed region
    phantom[cursor_bar + 1 :] = 1  # long after the cursor: reverses the phantom short

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        # Window 1 is flat, so the ledger holds no position at the bar-24 cursor.
        state, _ = run(
            "x",
            _slice_md(data, slice(0, cursor_bar + 1)),
            _slice_sig(from_target(window1), slice(0, cursor_bar + 1)),
            cfg,
            db_path=db,
            aux_data=aux,
        )
        assert state.open_position is None
        # Window 2 replays from bar 0 (the ATR warmup reaches back past the phantom at bar 10).
        state, _ = run(
            "x",
            _slice_md(data, slice(0, n)),
            _slice_sig(from_target(phantom), slice(0, n)),
            cfg,
            db_path=db,
            aux_data=aux,
        )

    assert state is not None
    all_ts = [int(t) for t in np.asarray(data.timestamps.as_unit("ns").asi8, dtype=np.int64)]
    flip_bar = cursor_bar + 1
    # Exactly one long entry on the flip bar. Without the guard the replay also opens the
    # phantom short inside the committed region, so the strategy's *close* of it lands on the
    # flip bar too — where the `> cursor` filter keeps it — and the fold books a second buy
    # (the GBPUSD 151,908.92-unit first trade).
    long_entries = [
        e
        for e in state.ledger.events
        if e.event_type is EventType.FILL
        and int(e.side) == 1
        and int(e.timestamp) == all_ts[flip_bar]
    ]
    assert len(long_entries) == 1, (
        f"expected one long entry at bar {flip_bar}, got {len(long_entries)} "
        "(the phantom close was folded as a second entry)"
    )
    expected = 0.10 * 10_000.0 * 100.0 / float(data.close[flip_bar])
    booked_qty = abs(float(long_entries[0].quantity))
    assert booked_qty < 1.5 * expected, (
        f"long quantity {booked_qty:.4f} is doubled (expected ~{expected:.4f})"
    )


# ---------------------------------------------------------------------------
# full run vs. multi-window resume
# ---------------------------------------------------------------------------


def test_full_run_produces_flip_trades() -> None:
    got, open_pos = _run_windows([(0, 24)])
    assert [t[0] for t in got] == [1, -1]
    assert got[0][2] == 1_704_081_600_000_000_000  # bar-4 signal fills at bar 4 (same-bar close)
    assert got[1][3] == 1_704_132_000_000_000_000  # short closed by the bar-18 signal at bar 18
    assert open_pos is not None and open_pos.side == 1  # bar-20 long still open
    assert open_pos.entry_ns == 1_704_139_200_000_000_000  # bar-20 signal fills at bar 20


# Window plans for the reviewer boundary matrix (DEFECT-2 cases) and the vbt-style
# cascade carry/re-open cases. Window 1 ends on, around, and strictly before the flip /
# exit bars of the long and short legs; later windows overlap it and re-open the carried
# trade at (or after) its fill bar.
BOUNDS: list[list[tuple[int, int]]] = [
    [(0, 9), (4, 24)],
    [(0, 10), (4, 24)],
    [(0, 13), (4, 24)],
    [(0, 17), (4, 24)],
    [(0, 18), (4, 24)],
    [(0, 19), (4, 24)],  # window 1's LAST bar carries the short-exit signal in flight
    [(0, 11), (4, 24)],  # window 1 ends exactly on the flip fill bar
    [(0, 10), (4, 18), (9, 24)],  # open carry; resume at the entry bar
    [(0, 12), (4, 20), (9, 24)],
    [(0, 6), (4, 14), (9, 24)],
    [(0, 11), (4, 20), (20, 24)],  # restart window 2 at the carried entry bar (4)
    [(0, 6), (4, 12), (10, 18), (10, 24)],  # dense overlap cascade, one bar re-run
]


@pytest.mark.parametrize("bounds", BOUNDS)
def test_split_windows_match_full_run(bounds: list[tuple[int, int]]) -> None:
    full, full_open = _run_windows([(0, 24)])
    got, open_pos = _run_windows(bounds)
    assert got == full
    assert open_pos == full_open


@pytest.mark.parametrize("bounds", BOUNDS)
def test_split_windows_reproduce_the_full_ledger(bounds: list[tuple[int, int]]) -> None:
    # DEFECT 2, authoritative form: folding the history into overlapping paper windows must
    # reproduce the persisted ledger EVENT-FOR-EVENT of a single full-window run — every
    # fill/commission, every funding_payment (including accrual across a carried leg), and
    # every position_change step, not just the derived trade summary. This is the
    # property that broke: carried legs reported window-relative position_after, and
    # funding rows at the window seams were mis-sized or missing.
    full_state = _run_windows_state([(0, 24)])
    got_state = _run_windows_state(bounds)
    assert _ledger_tokens(got_state) == _ledger_tokens(full_state)
    assert got_state.open_position == full_state.open_position


def test_carried_entry_is_not_double_booked() -> None:
    # DEFECT 1: re-running the carried entry as a normal order would book a *second* fill
    # one bar after the real one (backtrader fills at next-bar open), doubling the
    # position. The carried entry must be seeded verbatim, never re-executed.
    target = np.zeros(24, dtype=int)
    target[4:10] = 1
    got = _run_windows([(0, 6), (4, 24)], target=target)
    full = _run_windows([(0, 24)], target=target)
    assert got == full
    assert [t[0] for t in got[0]] == [1]  # the long closes once at bar-11; no ghost short


@pytest.mark.parametrize("ac", ["forex", "commodities"])
def test_leveraged_multi_window_resume_never_doubles_first_quantity(ac: str) -> None:
    # Live POC regression: the stale build resumed an open leg over overlapping windows and
    # re-booked the carried entry, so the first trade printed 2x (gold 46.0 vs ~23.8 units;
    # GBPUSD 150,773.29 vs ~75,388 base). With fixed_fraction 0.10 + leverage 100, a seed
    # window followed by overlapping resume windows must produce exactly the full-window
    # ledger — same rows, same quantities (the carried entry is seeded, never re-executed).
    preset = PRESETS[ac]
    data = synthetic_bars(preset, n_bars=24)
    target = np.zeros(24, dtype=int)
    target[4:10] = 1
    target[10:18] = -1
    signals = from_target(target)
    risk = RiskConfig(
        sizing=SizeModel(kind="fixed_fraction", value=0.10, leverage=100.0),
        exit=(
            StopLoss(percent=0.02, trigger="touched"),
            TakeProfit(percent=0.02, trigger="touched"),
            ATRStop(atr="atr_1m", period=14, mult=1.5, trailing=False, trigger="touched"),
        ),
    )
    cfg = PaperConfig(
        base=BacktestConfig(
            instrument=preset.instrument,
            risk=risk,
            signal=SignalConfig(on_opposite_signal="reverse"),
        ),
        engine="backtrader",
        starting_balance=10_000.0,
    )
    aux = {"atr_1m": data}

    def quantities(bounds: list[tuple[int, int]]) -> list[tuple[int, float]]:
        import tempfile
        from pathlib import Path

        with tempfile.TemporaryDirectory() as td:
            db = str(Path(td) / "s.db")
            init(cfg, run_id="x", db_path=db)
            state: BacktraderPaperState | None = None
            for a, b in bounds:
                state, _ = run(
                    "x",
                    _slice_md(data, slice(a, b)),
                    _slice_sig(signals, slice(a, b)),
                    cfg,
                    db_path=db,
                    aux_data=aux,
                )
        assert state is not None
        instr = cfg.base.instrument
        return [
            (int(t.side), round(float(t.quantity), 6))
            for t in trades(state.ledger, instruments={instr.symbol: instr})
        ]

    full = quantities([(0, 24)])
    windows = quantities([(0, 6), (4, 18), (4, 24)])
    assert windows == full, f"{ac}: windowed resume doubled a quantity ({windows} vs {full})"
    assert full, f"{ac}: expected at least one booked trade"
    first_qty = abs(full[0][1])
    expected = 0.10 * 10_000.0 * 100.0 / float(data.close[4])
    assert first_qty < 2.0 * expected + 1e-6, (
        f"{ac}: first quantity {first_qty:.4f} looks doubled (expected ~{expected:.4f})"
    )


def test_final_bar_exit_in_flight_fills_at_the_final_close() -> None:
    # A short-exit SIGNAL on window 1's very last bar (bar 18) fills at the bar-18 close,
    # exactly like a single full-window run: the references fill a signal exit at the same
    # bar's close. backtrader's broker would execute it at bar 19's open, so ``stop()``
    # realizes the in-flight exit at the final bar's close (reason attached) instead of
    # leaving it open or dropping it.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    target = _target_full_run()
    signals = from_target(target)
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        state, _ = run(
            "x", _slice_md(data, slice(0, 19)), _slice_sig(signals, slice(0, 19)), cfg, db_path=db
        )
        # The short entered at bar 10 is closed by the bar-18 exit at its close.
        assert state.open_position is None
        state, _ = run(
            "x", _slice_md(data, slice(4, 24)), _slice_sig(signals, slice(4, 24)), cfg, db_path=db
        )

    got = _summary(state, cfg)
    full, full_open = _run_windows([(0, 24)])
    assert got == full
    assert state.open_position == full_open


def _dip_on_entry_bar_md(lows: list[float]) -> MarketData:
    """Flat 100s with a caller-chosen low per bar, on gold's session timestamps.

    The long the tests below carry in is filled at the *close* of bar 0 (a same-bar close
    fill, §8), so a low that dips through the 95 stop was reached *before* the position
    existed and must not fire it - exactly as in a full run, where ``notify_order`` builds
    the plan on the fill bar and ``next()`` first consults it on the NEXT one.
    """
    n = len(lows)
    return MarketData(
        open=np.full(n, 100.0),
        high=np.full(n, 101.0),
        low=np.array(lows, dtype=float),
        close=np.full(n, 100.0),
        volume=np.full(n, 100.0),
        index=synthetic_bars(PRESETS["commodities"], n_bars=n).index,
    )


def _touched_stop_config(starting_balance: float = 10_000.0) -> PaperConfig:
    """A ``commodities`` (gold-shaped) config with a touched 5% stop - the live path.

    The leveraged sizing matches ``test_leveraged_multi_window_resume_never_doubles_first_quantity``
    so the venue funds a held leg and its replacement on the same bar; a cash-only CFD balance
    would run the broker dry on the cover and silently drop the flip's entry leg instead.
    Free of the funding accrual a perp pays at a window seam, too.
    """
    return PaperConfig(
        base=BacktestConfig(
            instrument=PRESETS["commodities"].instrument,
            risk=RiskConfig(
                sizing=SizeModel(kind="fixed_fraction", value=0.10, leverage=100.0),
                exit=(StopLoss(percent=0.05),),
            ),
            signal=SignalConfig(on_opposite_signal="reverse"),
        ),
        engine="backtrader",
        starting_balance=starting_balance,
    )


def _run_md_windows(
    data: MarketData,
    signals: Signals,
    cfg: PaperConfig,
    bounds: list[tuple[int, int]],
) -> BacktraderPaperState:
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        state: BacktraderPaperState | None = None
        for a, b in bounds:
            state, _ = run(
                "x",
                _slice_md(data, slice(a, b)),
                _slice_sig(signals, slice(a, b)),
                cfg,
                db_path=db,
            )
    assert state is not None
    return state


def test_carried_position_ignores_stop_touched_on_its_own_entry_bar() -> None:
    # A warm window restarts AT the carried position's fill bar (that is the resume
    # contract), so bar 0 of the window IS the entry bar, low and all. If the carried plan is
    # armed from bar 0 the window stops the carried long out on the very bar it was entered
    # - a phantom exit whose events fall at or before the cursor and are dropped, so the
    # fold keeps a long the strategy already considers flat. The next flip then opens the
    # short WITHOUT covering it, and the realized cash drifts, so every later size diverges
    # from a single full-window run. Bar 0's dip to 90 is below the 95 stop; bars 1+ are
    # clear of it, so the stop must never fire at all.
    data = _dip_on_entry_bar_md([90.0, 99.0, 99.0, 99.0])
    signals = from_target(np.array([1, -1, -1, -1]))
    cfg = _touched_stop_config()

    full = _run_md_windows(data, signals, cfg, [(0, 4)])
    # Window 1 fills the long at bar 0 and leaves it carried; window 2 replays from its entry
    # bar, where bar 0's dip would otherwise stop the carried trade out.
    got = _run_md_windows(data, signals, cfg, [(0, 1), (0, 4)])

    assert _ledger_tokens(got) == _ledger_tokens(full)
    assert got.open_position == full.open_position
    # Sanity: no stop ever fired, the long covered into the short exactly once, and the
    # short is what is left open.
    assert not [t for t in got.ledger.events if t.exit_reason == "stop_loss"]
    assert _summary(got, cfg) == _summary(full, cfg)
    assert [t[0] for t in _summary(got, cfg)] == [1]
    assert got.open_position is not None and got.open_position.side == -1


def test_seam_bar_touched_exit_fills_at_the_exit_level() -> None:
    # A touched risk exit submitted on a window's LAST bar cannot fill through backtrader's
    # broker (market orders fill at the next bar's open), so ``stop()`` books it - and it must
    # book it at the exit LEVEL, exactly as ``notify_order`` would have, not at that bar's
    # close. Here the level is 95 while the bar closes at 100, so a close-fill would inflate
    # the realized PnL and diverge from the single full-window run that books it at 95.
    data = _dip_on_entry_bar_md([90.0, 99.0, 99.0, 94.0])
    signals = from_target(np.ones(4, dtype=int))
    cfg = _touched_stop_config()

    full = _run_md_windows(data, signals, cfg, [(0, 4)])
    # Window 1 stops on bar 2 with the long open; window 2 replays from the entry bar and the
    # stop fires on its final bar (bar 3) in flight.
    got = _run_md_windows(data, signals, cfg, [(0, 3), (0, 4)])

    assert _ledger_tokens(got) == _ledger_tokens(full)
    assert got.open_position == full.open_position
    exits = [t for t in got.ledger.events if t.exit_reason == "stop_loss"]
    assert exits and _r(exits[0].price) == pytest.approx(95.0)
    assert _summary(got, cfg) == _summary(full, cfg)



def test_resume_requires_entry_bar_in_window() -> None:
    # After window 1 (bars 0..9) the long signalled at bar 4 was filled at bar 5 and is
    # still open. A window that starts after bar 5 (i.e. omits the carried entry's fill
    # bar) cannot re-open the carried trade.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    target = np.zeros(24, dtype=int)
    target[4:10] = 1
    target[10:18] = -1
    signals = from_target(target)
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        run("x", _slice_md(data, slice(0, 10)), _slice_sig(signals, slice(0, 10)), cfg, db_path=db)
        with pytest.raises(EngineError, match="carried entry"):
            run(
                "x",
                _slice_md(data, slice(6, 24)),
                _slice_sig(signals, slice(6, 24)),
                cfg,
                db_path=db,
            )


def test_resume_carries_entry_when_signal_fn_does_not_reemit_it() -> None:
    # Crash-2 regression (backtrader mirror): the live worker died when a *stateful* signal
    # function could not reproduce the carried entry over the recomputed window. The
    # persisted ledger is authoritative, so the backend must carry the open trade forward
    # (with a warning) instead of aborting.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    # Window 1 (bars 0..11): the wall-clock fn originally emitted a long entry at bar 3
    # (fills at bar 4) and holds it — the reference leg we must resume.
    first = from_target(np.array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
    # Window 2: the same "wall-clock minute" re-derives a FLAT signal at bar 3 (the entry
    # is not re-emitted at its own bar), but the next leg — a short at bar 15 — is.
    signal_fn_target = np.zeros(24, dtype=int)
    signal_fn_target[15:20] = -1
    signals = from_target(signal_fn_target)
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        run("x", _slice_md(data, slice(0, 12)), _slice_sig(first, slice(0, 12)), cfg, db_path=db)
        # Window 2 restarts at the carried entry bar (bar 3); the wall-clock fn re-derives
        # a flat signal there, so the window must be carried from the ledger, not crash.
        with pytest.warns(UserWarning, match="not re-emitted"):
            state, _ = run(
                "x",
                _slice_md(data, slice(3, 24)),
                _slice_sig(signals, slice(3, 24)),
                cfg,
                db_path=db,
            )

    got = _summary(state, cfg)
    # Long signalled bar 3 (fills bar 3), flipped short at bar 15 (fills bar 15), closed
    # by bar 20's 0 (fills bar 20) — both legs survive the carry.
    assert [t[0] for t in got] == [1, -1]
    assert got[0][2] == 1_704_078_000_000_000_000  # bar-3 signal fills at bar 3
    assert got[1][3] == 1_704_139_200_000_000_000  # bar-20 signal fills at bar 20
    assert state.open_position is None  # the bar-15 short is closed by bar 20's 0


def test_gapped_resume_does_not_double_book_starting_balance() -> None:
    # Regression: a warm window whose first bar falls strictly after the cursor (a data
    # gap right after the flat last-close bar) used to leak the window-start
    # ``+starting_balance`` cash event into the persisted ledger on every resume.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    # Window 1: long signalled at bar 4 (fills bar 5), closed (flat) at bar 9's signal
    # (fills bar 10).
    first = from_target(np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0]))
    cfg = _config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        run("x", _slice_md(data, slice(0, 12)), _slice_sig(first, slice(0, 12)), cfg, db_path=db)
        # Window 2 SKIPS bars 10-11 and re-enters at bar 12 — the resume window starts at
        # bar 12, strictly after the cursor.
        second_full = np.zeros(24, dtype=int)
        second_full[12:18] = 1
        second = from_target(second_full)
        state, _ = run(
            "x",
            _slice_md(data, slice(12, 24)),
            _slice_sig(second, slice(12, 24)),
            cfg,
            db_path=db,
        )

    # The +10000 initial deposit may be booked EXACTLY ONCE.
    seeds = [
        e
        for e in state.ledger.events
        if e.event_type is EventType.CASH_MOVEMENT
        and e.amount is not None
        and abs(float(e.amount) - 10_000.0) < 1e-9
    ]
    assert len(seeds) == 1, (
        f"initial deposit booked {len(seeds)} times (double-booking leak): "
        f"{[c.amount for c in seeds]}"
    )


# ---------------------------------------------------------------------------
# ATR exits via aux_data (§5.2)
# ---------------------------------------------------------------------------


def _atr_config(**kw: object) -> PaperConfig:
    instr = PRESETS[AC].instrument
    bc = BacktestConfig(
        instrument=instr,
        signal=SignalConfig(on_opposite_signal="reverse"),
        risk=RiskConfig(exit=(ATRStop(mult=0.05, period=3, atr="atr_1m"),)),
    )
    return PaperConfig(base=bc, engine="backtrader", starting_balance=10_000.0, **kw)


def test_atr_exit_without_aux_data_fails_fast() -> None:
    # The adapter refuses an ATR exit whose named series is absent (never derives ATR from
    # the signal bars). The paper path must surface that, not silently drop the exit.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    signals = from_target(np.array([0, 0, 0, 0, 1] + [0] * 19))
    cfg = _atr_config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        with pytest.raises(EngineError, match="atr_1m"):
            run("x", data, signals, cfg, db_path=db)


def test_atr_exit_with_aux_data_closes_the_trade() -> None:
    # Same run with `aux_data={"atr_1m": md}` supplied: the named series resolves, the ATR
    # stop becomes a live sl_stop fraction, and the long is closed by the ATR stop.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    signals = from_target(np.array([0, 0, 0, 0, 1] + [0] * 19))
    cfg = _atr_config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        state, _ = run("x", data, signals, cfg, db_path=db, aux_data={"atr_1m": data})

    # aux is persisted for the next window to reuse (the engine also stamps its own ``bt``
    # marker key, so assert membership rather than the whole dict).
    assert "atr_1m" in state.aux_data
    assert isinstance(state.aux_data["atr_1m"], MarketData)

    got = _summary(state, cfg)
    assert got, "ATR stop never fired — the named aux series was not consumed"
    assert got[0][0] == 1
    assert state.open_position is None


def test_atr_exit_survives_windowed_resume_with_aux() -> None:
    # Split windows: the aux MarketData spans the full frame on every step, so the adapter
    # re-aligns it to each sliced window by timestamp. Without that re-alignment the
    # length check on the aux series would fail on the shorter window.
    data = synthetic_bars(PRESETS[AC], n_bars=24)
    signals = from_target(np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1] + [0] * 12))
    cfg = _atr_config()
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        db = str(Path(td) / "s.db")
        init(cfg, run_id="x", db_path=db)
        run(
            "x",
            _slice_md(data, slice(0, 12)),
            _slice_sig(signals, slice(0, 12)),
            cfg,
            db_path=db,
            aux_data={"atr_1m": data},
        )
        state, _ = run(
            "x",
            _slice_md(data, slice(0, 24)),
            _slice_sig(signals, slice(0, 24)),
            cfg,
            db_path=db,
            aux_data={"atr_1m": data},
        )

    assert state.open_position is None
